/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'Repair' : IDL.Null,
  'Servicing' : IDL.Null,
  'Installation' : IDL.Null,
});
export const ApplianceType = IDL.Variant({
  'HobChula' : IDL.Null,
  'Chimney' : IDL.Null,
  'Dryer' : IDL.Null,
  'WashingMachine' : IDL.Null,
  'Microwave' : IDL.Null,
  'Dishwasher' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'address' : IDL.Text,
  'applianceType' : ApplianceType,
  'phone' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const TestimonialStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'status' : TestimonialStatus,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const BookingCounts = IDL.Record({
  'cancelled' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'confirmed' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'applianceType' : ApplianceType,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingRequest], [BookingId], []),
  'deleteBooking' : IDL.Func([BookingId], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBookingCounts' : IDL.Func([], [BookingCounts], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
  'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'Repair' : IDL.Null,
    'Servicing' : IDL.Null,
    'Installation' : IDL.Null,
  });
  const ApplianceType = IDL.Variant({
    'HobChula' : IDL.Null,
    'Chimney' : IDL.Null,
    'Dryer' : IDL.Null,
    'WashingMachine' : IDL.Null,
    'Microwave' : IDL.Null,
    'Dishwasher' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'address' : IDL.Text,
    'applianceType' : ApplianceType,
    'phone' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const TestimonialStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'status' : TestimonialStatus,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const BookingCounts = IDL.Record({
    'cancelled' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'confirmed' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'applianceType' : ApplianceType,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingRequest], [BookingId], []),
    'deleteBooking' : IDL.Func([BookingId], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBookingCounts' : IDL.Func([], [BookingCounts], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [], []),
    'updateTestimonialStatus' : IDL.Func([IDL.Nat, TestimonialStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };