/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export interface BookingRequest {
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    applianceType: ApplianceType;
    phone: string;
}
export interface BookingCounts {
    cancelled: bigint;
    pending: bigint;
    completed: bigint;
    confirmed: bigint;
}
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    timestamp: bigint;
    applianceType: ApplianceType;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: bigint;
    status: TestimonialStatus;
    content: string;
    author: string;
    timestamp: bigint;
    rating: bigint;
}
export enum ApplianceType {
    HobChula = "HobChula",
    Chimney = "Chimney",
    Dryer = "Dryer",
    WashingMachine = "WashingMachine",
    Microwave = "Microwave",
    Dishwasher = "Dishwasher"
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum ServiceType {
    Repair = "Repair",
    Servicing = "Servicing",
    Installation = "Installation"
}
export enum TestimonialStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(request: BookingRequest): Promise<BookingId>;
    deleteBooking(bookingId: BookingId): Promise<void>;
    deleteTestimonial(id: bigint): Promise<void>;
    getApprovedTestimonials(): Promise<Array<Testimonial>>;
    getBookingCounts(): Promise<BookingCounts>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPendingTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitTestimonial(author: string, content: string, rating: bigint): Promise<void>;
    updateBookingStatus(bookingId: BookingId, status: BookingStatus): Promise<void>;
    updateTestimonialStatus(id: bigint, status: TestimonialStatus): Promise<void>;
}
import type { ApplianceType as _ApplianceType, Booking as _Booking, BookingId as _BookingId, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, ServiceType as _ServiceType, Testimonial as _Testimonial, TestimonialStatus as _TestimonialStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: BookingRequest): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBooking(arg0: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getApprovedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonials();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonials();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingCounts(): Promise<BookingCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingCounts();
            return result;
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTestimonials();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTestimonials();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestimonialStatus(arg0: bigint, arg1: TestimonialStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonialStatus(arg0, to_candid_TestimonialStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonialStatus(arg0, to_candid_TestimonialStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApplianceType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplianceType): ApplianceType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TestimonialStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestimonialStatus): TestimonialStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TestimonialStatus;
    content: string;
    author: string;
    timestamp: bigint;
    rating: bigint;
}): {
    id: bigint;
    status: TestimonialStatus;
    content: string;
    author: string;
    timestamp: bigint;
    rating: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TestimonialStatus_n12(_uploadFile, _downloadFile, value.status),
        content: value.content,
        author: value.author,
        timestamp: value.timestamp,
        rating: value.rating
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    serviceType: _ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    timestamp: bigint;
    applianceType: _ApplianceType;
    phone: string;
}): {
    id: BookingId;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    timestamp: bigint;
    applianceType: ApplianceType;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n17(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n19(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        description: value.description,
        email: value.email,
        preferredDate: value.preferredDate,
        address: value.address,
        timestamp: value.timestamp,
        applianceType: from_candid_ApplianceType_n21(_uploadFile, _downloadFile, value.applianceType),
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TestimonialStatus {
    return "pending" in value ? TestimonialStatus.pending : "approved" in value ? TestimonialStatus.approved : "rejected" in value ? TestimonialStatus.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Repair: null;
} | {
    Servicing: null;
} | {
    Installation: null;
}): ServiceType {
    return "Repair" in value ? ServiceType.Repair : "Servicing" in value ? ServiceType.Servicing : "Installation" in value ? ServiceType.Installation : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HobChula: null;
} | {
    Chimney: null;
} | {
    Dryer: null;
} | {
    WashingMachine: null;
} | {
    Microwave: null;
} | {
    Dishwasher: null;
}): ApplianceType {
    return "HobChula" in value ? ApplianceType.HobChula : "Chimney" in value ? ApplianceType.Chimney : "Dryer" in value ? ApplianceType.Dryer : "WashingMachine" in value ? ApplianceType.WashingMachine : "Microwave" in value ? ApplianceType.Microwave : "Dishwasher" in value ? ApplianceType.Dishwasher : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ApplianceType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplianceType): _ApplianceType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_BookingRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequest): _BookingRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TestimonialStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialStatus): _TestimonialStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    applianceType: ApplianceType;
    phone: string;
}): {
    serviceType: _ServiceType;
    name: string;
    description: string;
    email: string;
    preferredDate: string;
    address: string;
    applianceType: _ApplianceType;
    phone: string;
} {
    return {
        serviceType: to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        description: value.description,
        email: value.email,
        preferredDate: value.preferredDate,
        address: value.address,
        applianceType: to_candid_ApplianceType_n7(_uploadFile, _downloadFile, value.applianceType),
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == TestimonialStatus.pending ? {
        pending: null
    } : value == TestimonialStatus.approved ? {
        approved: null
    } : value == TestimonialStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    Repair: null;
} | {
    Servicing: null;
} | {
    Installation: null;
} {
    return value == ServiceType.Repair ? {
        Repair: null
    } : value == ServiceType.Servicing ? {
        Servicing: null
    } : value == ServiceType.Installation ? {
        Installation: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplianceType): {
    HobChula: null;
} | {
    Chimney: null;
} | {
    Dryer: null;
} | {
    WashingMachine: null;
} | {
    Microwave: null;
} | {
    Dishwasher: null;
} {
    return value == ApplianceType.HobChula ? {
        HobChula: null
    } : value == ApplianceType.Chimney ? {
        Chimney: null
    } : value == ApplianceType.Dryer ? {
        Dryer: null
    } : value == ApplianceType.WashingMachine ? {
        WashingMachine: null
    } : value == ApplianceType.Microwave ? {
        Microwave: null
    } : value == ApplianceType.Dishwasher ? {
        Dishwasher: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
